// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	AccountID   int32  `gorm:"column:account_id;primaryKey;autoIncrement:true" json:"account_id"`
	UserID      int32  `gorm:"column:user_id;not null" json:"user_id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description;not null" json:"description"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
