// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategoriesExpense = "categories_expenses"

// CategoriesExpense mapped from table <categories_expenses>
type CategoriesExpense struct {
	CategoryID  int32  `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	UserID      int32  `gorm:"column:user_id;not null" json:"user_id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description;not null" json:"description"`
}

// TableName CategoriesExpense's table name
func (*CategoriesExpense) TableName() string {
	return TableNameCategoriesExpense
}
