// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	GroupID     int32  `gorm:"column:group_id;primaryKey;autoIncrement:true" json:"group_id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description;not null" json:"description"`
	UserID      int32  `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
