// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLedgerTransfer = "ledger_transfer"

// LedgerTransfer mapped from table <ledger_transfer>
type LedgerTransfer struct {
	IDTransfer   int32     `gorm:"column:id_transfer;primaryKey;autoIncrement:true" json:"id_transfer"`
	IDAccountOut int32     `gorm:"column:id_account_out;not null" json:"id_account_out"`
	IDAccountIn  int32     `gorm:"column:id_account_in;not null" json:"id_account_in"`
	Descripcion  string    `gorm:"column:descripcion;not null;default:Transferencia" json:"descripcion"`
	Amount       float64   `gorm:"column:amount;not null" json:"amount"`
	Date         time.Time `gorm:"column:date;not null;default:curdate()" json:"date"`
}

// TableName LedgerTransfer's table name
func (*LedgerTransfer) TableName() string {
	return TableNameLedgerTransfer
}
