// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLedgerExpense = "ledger_expenses"

// LedgerExpense mapped from table <ledger_expenses>
type LedgerExpense struct {
	IDExpense         int32     `gorm:"column:id_expense;primaryKey;autoIncrement:true" json:"id_expense"`
	AccountID         int32     `gorm:"column:account_id;not null" json:"account_id"`
	GroupID           int32     `gorm:"column:group_id;not null" json:"group_id"`
	ExpenseCategoryID int32     `gorm:"column:expense_category_id;not null" json:"expense_category_id"`
	Description       string    `gorm:"column:description;not null" json:"description"`
	Amount            float64   `gorm:"column:amount;not null" json:"amount"`
	Date              time.Time `gorm:"column:date;not null;default:curdate()" json:"date"`
}

// TableName LedgerExpense's table name
func (*LedgerExpense) TableName() string {
	return TableNameLedgerExpense
}
