// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLedgerIncome = "ledger_incomes"

// LedgerIncome mapped from table <ledger_incomes>
type LedgerIncome struct {
	IDIncome         int32     `gorm:"column:id_income;primaryKey;autoIncrement:true" json:"id_income"`
	AccountID        int32     `gorm:"column:account_id;not null" json:"account_id"`
	GroupID          int32     `gorm:"column:group_id;not null" json:"group_id"`
	IncomeCategoryID int32     `gorm:"column:income_category_id;not null" json:"income_category_id"`
	Description      string    `gorm:"column:description;not null" json:"description"`
	Amount           float64   `gorm:"column:amount;not null" json:"amount"`
	Date             time.Time `gorm:"column:date;not null;default:curdate()" json:"date"`
}

// TableName LedgerIncome's table name
func (*LedgerIncome) TableName() string {
	return TableNameLedgerIncome
}
