// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLedgerSaving = "ledger_savings"

// LedgerSaving mapped from table <ledger_savings>
type LedgerSaving struct {
	IDSaving         int32     `gorm:"column:id_saving;primaryKey;autoIncrement:true" json:"id_saving"`
	AccountID        int32     `gorm:"column:account_id;not null" json:"account_id"`
	GroupID          int32     `gorm:"column:group_id;not null" json:"group_id"`
	SavingCategoryID int32     `gorm:"column:saving_category_id;not null" json:"saving_category_id"`
	Description      string    `gorm:"column:description;not null" json:"description"`
	Amount           float64   `gorm:"column:amount;not null" json:"amount"`
	Date             time.Time `gorm:"column:date;not null;default:curdate()" json:"date"`
}

// TableName LedgerSaving's table name
func (*LedgerSaving) TableName() string {
	return TableNameLedgerSaving
}
