// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTotalPerMonthGroup = "total_per_month_groups"

// TotalPerMonthGroup mapped from table <total_per_month_groups>
type TotalPerMonthGroup struct {
	Month        int32   `gorm:"column:Month" json:"Month"`
	Year         int32   `gorm:"column:Year" json:"Year"`
	Group_       string  `gorm:"column:group;not null" json:"group"`
	Usuario      int32   `gorm:"column:usuario;not null" json:"usuario"`
	TotalIncome  float64 `gorm:"column:Total income" json:"Total income"`
	TotalExpense float64 `gorm:"column:Total expense" json:"Total expense"`
	Total        float64 `gorm:"column:Total" json:"Total"`
}

// TableName TotalPerMonthGroup's table name
func (*TotalPerMonthGroup) TableName() string {
	return TableNameTotalPerMonthGroup
}
