// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTotalPerMonthAccount = "total_per_month_accounts"

// TotalPerMonthAccount mapped from table <total_per_month_accounts>
type TotalPerMonthAccount struct {
	Month        int32   `gorm:"column:Month" json:"Month"`
	Year         int32   `gorm:"column:Year" json:"Year"`
	Account      string  `gorm:"column:account;not null" json:"account"`
	Usuario      int32   `gorm:"column:usuario;not null" json:"usuario"`
	TotalIncome  float64 `gorm:"column:Total income" json:"Total income"`
	TotalExpense float64 `gorm:"column:Total expense" json:"Total expense"`
	TotalSaving  float64 `gorm:"column:Total saving" json:"Total saving"`
	Total        float64 `gorm:"column:Total" json:"Total"`
}

// TableName TotalPerMonthAccount's table name
func (*TotalPerMonthAccount) TableName() string {
	return TableNameTotalPerMonthAccount
}
