// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTotalInAccount = "total_in_accounts"

// TotalInAccount mapped from table <total_in_accounts>
type TotalInAccount struct {
	Account      string  `gorm:"column:account;not null" json:"account"`
	Usuario      int32   `gorm:"column:usuario;not null" json:"usuario"`
	TotalIncome  float64 `gorm:"column:Total income" json:"Total income"`
	TotalExpense float64 `gorm:"column:Total expense" json:"Total expense"`
	TotalSaving  float64 `gorm:"column:Total Saving" json:"Total Saving"`
	Total        float64 `gorm:"column:Total" json:"Total"`
}

// TableName TotalInAccount's table name
func (*TotalInAccount) TableName() string {
	return TableNameTotalInAccount
}
