// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID    int32  `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Firstname string `gorm:"column:firstname;not null" json:"firstname"`
	Lastname  string `gorm:"column:lastname;not null" json:"lastname"`
	Username  string `gorm:"column:username;not null" json:"username"`
	Password  string `gorm:"column:password;not null" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
