// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cdlavacudeg/go-budget-guardian/model"
)

func newCategoriesIncome(db *gorm.DB, opts ...gen.DOOption) categoriesIncome {
	_categoriesIncome := categoriesIncome{}

	_categoriesIncome.categoriesIncomeDo.UseDB(db, opts...)
	_categoriesIncome.categoriesIncomeDo.UseModel(&model.CategoriesIncome{})

	tableName := _categoriesIncome.categoriesIncomeDo.TableName()
	_categoriesIncome.ALL = field.NewAsterisk(tableName)
	_categoriesIncome.CategoryID = field.NewInt32(tableName, "category_id")
	_categoriesIncome.UserID = field.NewInt32(tableName, "user_id")
	_categoriesIncome.Name = field.NewString(tableName, "name")
	_categoriesIncome.Description = field.NewString(tableName, "description")

	_categoriesIncome.fillFieldMap()

	return _categoriesIncome
}

type categoriesIncome struct {
	categoriesIncomeDo

	ALL         field.Asterisk
	CategoryID  field.Int32
	UserID      field.Int32
	Name        field.String
	Description field.String

	fieldMap map[string]field.Expr
}

func (c categoriesIncome) Table(newTableName string) *categoriesIncome {
	c.categoriesIncomeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c categoriesIncome) As(alias string) *categoriesIncome {
	c.categoriesIncomeDo.DO = *(c.categoriesIncomeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *categoriesIncome) updateTableName(table string) *categoriesIncome {
	c.ALL = field.NewAsterisk(table)
	c.CategoryID = field.NewInt32(table, "category_id")
	c.UserID = field.NewInt32(table, "user_id")
	c.Name = field.NewString(table, "name")
	c.Description = field.NewString(table, "description")

	c.fillFieldMap()

	return c
}

func (c *categoriesIncome) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *categoriesIncome) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["name"] = c.Name
	c.fieldMap["description"] = c.Description
}

func (c categoriesIncome) clone(db *gorm.DB) categoriesIncome {
	c.categoriesIncomeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c categoriesIncome) replaceDB(db *gorm.DB) categoriesIncome {
	c.categoriesIncomeDo.ReplaceDB(db)
	return c
}

type categoriesIncomeDo struct{ gen.DO }

func (c categoriesIncomeDo) Debug() *categoriesIncomeDo {
	return c.withDO(c.DO.Debug())
}

func (c categoriesIncomeDo) WithContext(ctx context.Context) *categoriesIncomeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categoriesIncomeDo) ReadDB() *categoriesIncomeDo {
	return c.Clauses(dbresolver.Read)
}

func (c categoriesIncomeDo) WriteDB() *categoriesIncomeDo {
	return c.Clauses(dbresolver.Write)
}

func (c categoriesIncomeDo) Session(config *gorm.Session) *categoriesIncomeDo {
	return c.withDO(c.DO.Session(config))
}

func (c categoriesIncomeDo) Clauses(conds ...clause.Expression) *categoriesIncomeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categoriesIncomeDo) Returning(value interface{}, columns ...string) *categoriesIncomeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categoriesIncomeDo) Not(conds ...gen.Condition) *categoriesIncomeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c categoriesIncomeDo) Or(conds ...gen.Condition) *categoriesIncomeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c categoriesIncomeDo) Select(conds ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c categoriesIncomeDo) Where(conds ...gen.Condition) *categoriesIncomeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c categoriesIncomeDo) Order(conds ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c categoriesIncomeDo) Distinct(cols ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categoriesIncomeDo) Omit(cols ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categoriesIncomeDo) Join(table schema.Tabler, on ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categoriesIncomeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categoriesIncomeDo) RightJoin(table schema.Tabler, on ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categoriesIncomeDo) Group(cols ...field.Expr) *categoriesIncomeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c categoriesIncomeDo) Having(conds ...gen.Condition) *categoriesIncomeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c categoriesIncomeDo) Limit(limit int) *categoriesIncomeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c categoriesIncomeDo) Offset(offset int) *categoriesIncomeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c categoriesIncomeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *categoriesIncomeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categoriesIncomeDo) Unscoped() *categoriesIncomeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c categoriesIncomeDo) Create(values ...*model.CategoriesIncome) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categoriesIncomeDo) CreateInBatches(values []*model.CategoriesIncome, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categoriesIncomeDo) Save(values ...*model.CategoriesIncome) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categoriesIncomeDo) First() (*model.CategoriesIncome, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesIncome), nil
	}
}

func (c categoriesIncomeDo) Take() (*model.CategoriesIncome, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesIncome), nil
	}
}

func (c categoriesIncomeDo) Last() (*model.CategoriesIncome, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesIncome), nil
	}
}

func (c categoriesIncomeDo) Find() ([]*model.CategoriesIncome, error) {
	result, err := c.DO.Find()
	return result.([]*model.CategoriesIncome), err
}

func (c categoriesIncomeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CategoriesIncome, err error) {
	buf := make([]*model.CategoriesIncome, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categoriesIncomeDo) FindInBatches(result *[]*model.CategoriesIncome, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categoriesIncomeDo) Attrs(attrs ...field.AssignExpr) *categoriesIncomeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categoriesIncomeDo) Assign(attrs ...field.AssignExpr) *categoriesIncomeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categoriesIncomeDo) Joins(fields ...field.RelationField) *categoriesIncomeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c categoriesIncomeDo) Preload(fields ...field.RelationField) *categoriesIncomeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c categoriesIncomeDo) FirstOrInit() (*model.CategoriesIncome, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesIncome), nil
	}
}

func (c categoriesIncomeDo) FirstOrCreate() (*model.CategoriesIncome, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoriesIncome), nil
	}
}

func (c categoriesIncomeDo) FindByPage(offset int, limit int) (result []*model.CategoriesIncome, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categoriesIncomeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c categoriesIncomeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c categoriesIncomeDo) Delete(models ...*model.CategoriesIncome) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *categoriesIncomeDo) withDO(do gen.Dao) *categoriesIncomeDo {
	c.DO = *do.(*gen.DO)
	return c
}
