// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cdlavacudeg/go-budget-guardian/model"
)

func newLedgerIncome(db *gorm.DB, opts ...gen.DOOption) ledgerIncome {
	_ledgerIncome := ledgerIncome{}

	_ledgerIncome.ledgerIncomeDo.UseDB(db, opts...)
	_ledgerIncome.ledgerIncomeDo.UseModel(&model.LedgerIncome{})

	tableName := _ledgerIncome.ledgerIncomeDo.TableName()
	_ledgerIncome.ALL = field.NewAsterisk(tableName)
	_ledgerIncome.IDIncome = field.NewInt32(tableName, "id_income")
	_ledgerIncome.AccountID = field.NewInt32(tableName, "account_id")
	_ledgerIncome.GroupID = field.NewInt32(tableName, "group_id")
	_ledgerIncome.IncomeCategoryID = field.NewInt32(tableName, "income_category_id")
	_ledgerIncome.Description = field.NewString(tableName, "description")
	_ledgerIncome.Amount = field.NewFloat64(tableName, "amount")
	_ledgerIncome.Date = field.NewTime(tableName, "date")

	_ledgerIncome.fillFieldMap()

	return _ledgerIncome
}

type ledgerIncome struct {
	ledgerIncomeDo

	ALL              field.Asterisk
	IDIncome         field.Int32
	AccountID        field.Int32
	GroupID          field.Int32
	IncomeCategoryID field.Int32
	Description      field.String
	Amount           field.Float64
	Date             field.Time

	fieldMap map[string]field.Expr
}

func (l ledgerIncome) Table(newTableName string) *ledgerIncome {
	l.ledgerIncomeDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l ledgerIncome) As(alias string) *ledgerIncome {
	l.ledgerIncomeDo.DO = *(l.ledgerIncomeDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *ledgerIncome) updateTableName(table string) *ledgerIncome {
	l.ALL = field.NewAsterisk(table)
	l.IDIncome = field.NewInt32(table, "id_income")
	l.AccountID = field.NewInt32(table, "account_id")
	l.GroupID = field.NewInt32(table, "group_id")
	l.IncomeCategoryID = field.NewInt32(table, "income_category_id")
	l.Description = field.NewString(table, "description")
	l.Amount = field.NewFloat64(table, "amount")
	l.Date = field.NewTime(table, "date")

	l.fillFieldMap()

	return l
}

func (l *ledgerIncome) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *ledgerIncome) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 7)
	l.fieldMap["id_income"] = l.IDIncome
	l.fieldMap["account_id"] = l.AccountID
	l.fieldMap["group_id"] = l.GroupID
	l.fieldMap["income_category_id"] = l.IncomeCategoryID
	l.fieldMap["description"] = l.Description
	l.fieldMap["amount"] = l.Amount
	l.fieldMap["date"] = l.Date
}

func (l ledgerIncome) clone(db *gorm.DB) ledgerIncome {
	l.ledgerIncomeDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l ledgerIncome) replaceDB(db *gorm.DB) ledgerIncome {
	l.ledgerIncomeDo.ReplaceDB(db)
	return l
}

type ledgerIncomeDo struct{ gen.DO }

func (l ledgerIncomeDo) Debug() *ledgerIncomeDo {
	return l.withDO(l.DO.Debug())
}

func (l ledgerIncomeDo) WithContext(ctx context.Context) *ledgerIncomeDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l ledgerIncomeDo) ReadDB() *ledgerIncomeDo {
	return l.Clauses(dbresolver.Read)
}

func (l ledgerIncomeDo) WriteDB() *ledgerIncomeDo {
	return l.Clauses(dbresolver.Write)
}

func (l ledgerIncomeDo) Session(config *gorm.Session) *ledgerIncomeDo {
	return l.withDO(l.DO.Session(config))
}

func (l ledgerIncomeDo) Clauses(conds ...clause.Expression) *ledgerIncomeDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l ledgerIncomeDo) Returning(value interface{}, columns ...string) *ledgerIncomeDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l ledgerIncomeDo) Not(conds ...gen.Condition) *ledgerIncomeDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l ledgerIncomeDo) Or(conds ...gen.Condition) *ledgerIncomeDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l ledgerIncomeDo) Select(conds ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l ledgerIncomeDo) Where(conds ...gen.Condition) *ledgerIncomeDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l ledgerIncomeDo) Order(conds ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l ledgerIncomeDo) Distinct(cols ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l ledgerIncomeDo) Omit(cols ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l ledgerIncomeDo) Join(table schema.Tabler, on ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l ledgerIncomeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l ledgerIncomeDo) RightJoin(table schema.Tabler, on ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l ledgerIncomeDo) Group(cols ...field.Expr) *ledgerIncomeDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l ledgerIncomeDo) Having(conds ...gen.Condition) *ledgerIncomeDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l ledgerIncomeDo) Limit(limit int) *ledgerIncomeDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l ledgerIncomeDo) Offset(offset int) *ledgerIncomeDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l ledgerIncomeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *ledgerIncomeDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l ledgerIncomeDo) Unscoped() *ledgerIncomeDo {
	return l.withDO(l.DO.Unscoped())
}

func (l ledgerIncomeDo) Create(values ...*model.LedgerIncome) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l ledgerIncomeDo) CreateInBatches(values []*model.LedgerIncome, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l ledgerIncomeDo) Save(values ...*model.LedgerIncome) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l ledgerIncomeDo) First() (*model.LedgerIncome, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerIncome), nil
	}
}

func (l ledgerIncomeDo) Take() (*model.LedgerIncome, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerIncome), nil
	}
}

func (l ledgerIncomeDo) Last() (*model.LedgerIncome, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerIncome), nil
	}
}

func (l ledgerIncomeDo) Find() ([]*model.LedgerIncome, error) {
	result, err := l.DO.Find()
	return result.([]*model.LedgerIncome), err
}

func (l ledgerIncomeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LedgerIncome, err error) {
	buf := make([]*model.LedgerIncome, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l ledgerIncomeDo) FindInBatches(result *[]*model.LedgerIncome, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l ledgerIncomeDo) Attrs(attrs ...field.AssignExpr) *ledgerIncomeDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l ledgerIncomeDo) Assign(attrs ...field.AssignExpr) *ledgerIncomeDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l ledgerIncomeDo) Joins(fields ...field.RelationField) *ledgerIncomeDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l ledgerIncomeDo) Preload(fields ...field.RelationField) *ledgerIncomeDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l ledgerIncomeDo) FirstOrInit() (*model.LedgerIncome, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerIncome), nil
	}
}

func (l ledgerIncomeDo) FirstOrCreate() (*model.LedgerIncome, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LedgerIncome), nil
	}
}

func (l ledgerIncomeDo) FindByPage(offset int, limit int) (result []*model.LedgerIncome, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l ledgerIncomeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l ledgerIncomeDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l ledgerIncomeDo) Delete(models ...*model.LedgerIncome) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *ledgerIncomeDo) withDO(do gen.Dao) *ledgerIncomeDo {
	l.DO = *do.(*gen.DO)
	return l
}
