// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cdlavacudeg/go-budget-guardian/model"
)

func newTotalPerMonthGroup(db *gorm.DB, opts ...gen.DOOption) totalPerMonthGroup {
	_totalPerMonthGroup := totalPerMonthGroup{}

	_totalPerMonthGroup.totalPerMonthGroupDo.UseDB(db, opts...)
	_totalPerMonthGroup.totalPerMonthGroupDo.UseModel(&model.TotalPerMonthGroup{})

	tableName := _totalPerMonthGroup.totalPerMonthGroupDo.TableName()
	_totalPerMonthGroup.ALL = field.NewAsterisk(tableName)
	_totalPerMonthGroup.Month = field.NewInt32(tableName, "Month")
	_totalPerMonthGroup.Year = field.NewInt32(tableName, "Year")
	_totalPerMonthGroup.Group_ = field.NewString(tableName, "group")
	_totalPerMonthGroup.Usuario = field.NewInt32(tableName, "usuario")
	_totalPerMonthGroup.TotalIncome = field.NewFloat64(tableName, "Total income")
	_totalPerMonthGroup.TotalExpense = field.NewFloat64(tableName, "Total expense")
	_totalPerMonthGroup.Total = field.NewFloat64(tableName, "Total")

	_totalPerMonthGroup.fillFieldMap()

	return _totalPerMonthGroup
}

type totalPerMonthGroup struct {
	totalPerMonthGroupDo

	ALL          field.Asterisk
	Month        field.Int32
	Year         field.Int32
	Group_       field.String
	Usuario      field.Int32
	TotalIncome  field.Float64
	TotalExpense field.Float64
	Total        field.Float64

	fieldMap map[string]field.Expr
}

func (t totalPerMonthGroup) Table(newTableName string) *totalPerMonthGroup {
	t.totalPerMonthGroupDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t totalPerMonthGroup) As(alias string) *totalPerMonthGroup {
	t.totalPerMonthGroupDo.DO = *(t.totalPerMonthGroupDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *totalPerMonthGroup) updateTableName(table string) *totalPerMonthGroup {
	t.ALL = field.NewAsterisk(table)
	t.Month = field.NewInt32(table, "Month")
	t.Year = field.NewInt32(table, "Year")
	t.Group_ = field.NewString(table, "group")
	t.Usuario = field.NewInt32(table, "usuario")
	t.TotalIncome = field.NewFloat64(table, "Total income")
	t.TotalExpense = field.NewFloat64(table, "Total expense")
	t.Total = field.NewFloat64(table, "Total")

	t.fillFieldMap()

	return t
}

func (t *totalPerMonthGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *totalPerMonthGroup) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["Month"] = t.Month
	t.fieldMap["Year"] = t.Year
	t.fieldMap["group"] = t.Group_
	t.fieldMap["usuario"] = t.Usuario
	t.fieldMap["Total income"] = t.TotalIncome
	t.fieldMap["Total expense"] = t.TotalExpense
	t.fieldMap["Total"] = t.Total
}

func (t totalPerMonthGroup) clone(db *gorm.DB) totalPerMonthGroup {
	t.totalPerMonthGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t totalPerMonthGroup) replaceDB(db *gorm.DB) totalPerMonthGroup {
	t.totalPerMonthGroupDo.ReplaceDB(db)
	return t
}

type totalPerMonthGroupDo struct{ gen.DO }

func (t totalPerMonthGroupDo) Debug() *totalPerMonthGroupDo {
	return t.withDO(t.DO.Debug())
}

func (t totalPerMonthGroupDo) WithContext(ctx context.Context) *totalPerMonthGroupDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t totalPerMonthGroupDo) ReadDB() *totalPerMonthGroupDo {
	return t.Clauses(dbresolver.Read)
}

func (t totalPerMonthGroupDo) WriteDB() *totalPerMonthGroupDo {
	return t.Clauses(dbresolver.Write)
}

func (t totalPerMonthGroupDo) Session(config *gorm.Session) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Session(config))
}

func (t totalPerMonthGroupDo) Clauses(conds ...clause.Expression) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t totalPerMonthGroupDo) Returning(value interface{}, columns ...string) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t totalPerMonthGroupDo) Not(conds ...gen.Condition) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t totalPerMonthGroupDo) Or(conds ...gen.Condition) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t totalPerMonthGroupDo) Select(conds ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t totalPerMonthGroupDo) Where(conds ...gen.Condition) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t totalPerMonthGroupDo) Order(conds ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t totalPerMonthGroupDo) Distinct(cols ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t totalPerMonthGroupDo) Omit(cols ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t totalPerMonthGroupDo) Join(table schema.Tabler, on ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t totalPerMonthGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t totalPerMonthGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t totalPerMonthGroupDo) Group(cols ...field.Expr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t totalPerMonthGroupDo) Having(conds ...gen.Condition) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t totalPerMonthGroupDo) Limit(limit int) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t totalPerMonthGroupDo) Offset(offset int) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t totalPerMonthGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t totalPerMonthGroupDo) Unscoped() *totalPerMonthGroupDo {
	return t.withDO(t.DO.Unscoped())
}

func (t totalPerMonthGroupDo) Create(values ...*model.TotalPerMonthGroup) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t totalPerMonthGroupDo) CreateInBatches(values []*model.TotalPerMonthGroup, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t totalPerMonthGroupDo) Save(values ...*model.TotalPerMonthGroup) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t totalPerMonthGroupDo) First() (*model.TotalPerMonthGroup, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerMonthGroup), nil
	}
}

func (t totalPerMonthGroupDo) Take() (*model.TotalPerMonthGroup, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerMonthGroup), nil
	}
}

func (t totalPerMonthGroupDo) Last() (*model.TotalPerMonthGroup, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerMonthGroup), nil
	}
}

func (t totalPerMonthGroupDo) Find() ([]*model.TotalPerMonthGroup, error) {
	result, err := t.DO.Find()
	return result.([]*model.TotalPerMonthGroup), err
}

func (t totalPerMonthGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TotalPerMonthGroup, err error) {
	buf := make([]*model.TotalPerMonthGroup, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t totalPerMonthGroupDo) FindInBatches(result *[]*model.TotalPerMonthGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t totalPerMonthGroupDo) Attrs(attrs ...field.AssignExpr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t totalPerMonthGroupDo) Assign(attrs ...field.AssignExpr) *totalPerMonthGroupDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t totalPerMonthGroupDo) Joins(fields ...field.RelationField) *totalPerMonthGroupDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t totalPerMonthGroupDo) Preload(fields ...field.RelationField) *totalPerMonthGroupDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t totalPerMonthGroupDo) FirstOrInit() (*model.TotalPerMonthGroup, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerMonthGroup), nil
	}
}

func (t totalPerMonthGroupDo) FirstOrCreate() (*model.TotalPerMonthGroup, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerMonthGroup), nil
	}
}

func (t totalPerMonthGroupDo) FindByPage(offset int, limit int) (result []*model.TotalPerMonthGroup, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t totalPerMonthGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t totalPerMonthGroupDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t totalPerMonthGroupDo) Delete(models ...*model.TotalPerMonthGroup) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *totalPerMonthGroupDo) withDO(do gen.Dao) *totalPerMonthGroupDo {
	t.DO = *do.(*gen.DO)
	return t
}
