// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cdlavacudeg/go-budget-guardian/model"
)

func newTotalPerCategoryGroupExpense(db *gorm.DB, opts ...gen.DOOption) totalPerCategoryGroupExpense {
	_totalPerCategoryGroupExpense := totalPerCategoryGroupExpense{}

	_totalPerCategoryGroupExpense.totalPerCategoryGroupExpenseDo.UseDB(db, opts...)
	_totalPerCategoryGroupExpense.totalPerCategoryGroupExpenseDo.UseModel(&model.TotalPerCategoryGroupExpense{})

	tableName := _totalPerCategoryGroupExpense.totalPerCategoryGroupExpenseDo.TableName()
	_totalPerCategoryGroupExpense.ALL = field.NewAsterisk(tableName)
	_totalPerCategoryGroupExpense.Year = field.NewInt32(tableName, "Year")
	_totalPerCategoryGroupExpense.Month = field.NewInt32(tableName, "Month")
	_totalPerCategoryGroupExpense.Usuario = field.NewInt32(tableName, "Usuario")
	_totalPerCategoryGroupExpense.Group_ = field.NewString(tableName, "Group")
	_totalPerCategoryGroupExpense.IDCat = field.NewInt32(tableName, "idCat")
	_totalPerCategoryGroupExpense.Categoria = field.NewString(tableName, "Categoria")
	_totalPerCategoryGroupExpense.Total = field.NewFloat64(tableName, "Total")

	_totalPerCategoryGroupExpense.fillFieldMap()

	return _totalPerCategoryGroupExpense
}

type totalPerCategoryGroupExpense struct {
	totalPerCategoryGroupExpenseDo

	ALL       field.Asterisk
	Year      field.Int32
	Month     field.Int32
	Usuario   field.Int32
	Group_    field.String
	IDCat     field.Int32
	Categoria field.String
	Total     field.Float64

	fieldMap map[string]field.Expr
}

func (t totalPerCategoryGroupExpense) Table(newTableName string) *totalPerCategoryGroupExpense {
	t.totalPerCategoryGroupExpenseDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t totalPerCategoryGroupExpense) As(alias string) *totalPerCategoryGroupExpense {
	t.totalPerCategoryGroupExpenseDo.DO = *(t.totalPerCategoryGroupExpenseDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *totalPerCategoryGroupExpense) updateTableName(table string) *totalPerCategoryGroupExpense {
	t.ALL = field.NewAsterisk(table)
	t.Year = field.NewInt32(table, "Year")
	t.Month = field.NewInt32(table, "Month")
	t.Usuario = field.NewInt32(table, "Usuario")
	t.Group_ = field.NewString(table, "Group")
	t.IDCat = field.NewInt32(table, "idCat")
	t.Categoria = field.NewString(table, "Categoria")
	t.Total = field.NewFloat64(table, "Total")

	t.fillFieldMap()

	return t
}

func (t *totalPerCategoryGroupExpense) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *totalPerCategoryGroupExpense) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["Year"] = t.Year
	t.fieldMap["Month"] = t.Month
	t.fieldMap["Usuario"] = t.Usuario
	t.fieldMap["Group"] = t.Group_
	t.fieldMap["idCat"] = t.IDCat
	t.fieldMap["Categoria"] = t.Categoria
	t.fieldMap["Total"] = t.Total
}

func (t totalPerCategoryGroupExpense) clone(db *gorm.DB) totalPerCategoryGroupExpense {
	t.totalPerCategoryGroupExpenseDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t totalPerCategoryGroupExpense) replaceDB(db *gorm.DB) totalPerCategoryGroupExpense {
	t.totalPerCategoryGroupExpenseDo.ReplaceDB(db)
	return t
}

type totalPerCategoryGroupExpenseDo struct{ gen.DO }

func (t totalPerCategoryGroupExpenseDo) Debug() *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Debug())
}

func (t totalPerCategoryGroupExpenseDo) WithContext(ctx context.Context) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t totalPerCategoryGroupExpenseDo) ReadDB() *totalPerCategoryGroupExpenseDo {
	return t.Clauses(dbresolver.Read)
}

func (t totalPerCategoryGroupExpenseDo) WriteDB() *totalPerCategoryGroupExpenseDo {
	return t.Clauses(dbresolver.Write)
}

func (t totalPerCategoryGroupExpenseDo) Session(config *gorm.Session) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Session(config))
}

func (t totalPerCategoryGroupExpenseDo) Clauses(conds ...clause.Expression) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t totalPerCategoryGroupExpenseDo) Returning(value interface{}, columns ...string) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t totalPerCategoryGroupExpenseDo) Not(conds ...gen.Condition) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t totalPerCategoryGroupExpenseDo) Or(conds ...gen.Condition) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t totalPerCategoryGroupExpenseDo) Select(conds ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t totalPerCategoryGroupExpenseDo) Where(conds ...gen.Condition) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t totalPerCategoryGroupExpenseDo) Order(conds ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t totalPerCategoryGroupExpenseDo) Distinct(cols ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t totalPerCategoryGroupExpenseDo) Omit(cols ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t totalPerCategoryGroupExpenseDo) Join(table schema.Tabler, on ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t totalPerCategoryGroupExpenseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t totalPerCategoryGroupExpenseDo) RightJoin(table schema.Tabler, on ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t totalPerCategoryGroupExpenseDo) Group(cols ...field.Expr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t totalPerCategoryGroupExpenseDo) Having(conds ...gen.Condition) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t totalPerCategoryGroupExpenseDo) Limit(limit int) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t totalPerCategoryGroupExpenseDo) Offset(offset int) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t totalPerCategoryGroupExpenseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t totalPerCategoryGroupExpenseDo) Unscoped() *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Unscoped())
}

func (t totalPerCategoryGroupExpenseDo) Create(values ...*model.TotalPerCategoryGroupExpense) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t totalPerCategoryGroupExpenseDo) CreateInBatches(values []*model.TotalPerCategoryGroupExpense, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t totalPerCategoryGroupExpenseDo) Save(values ...*model.TotalPerCategoryGroupExpense) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t totalPerCategoryGroupExpenseDo) First() (*model.TotalPerCategoryGroupExpense, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryGroupExpense), nil
	}
}

func (t totalPerCategoryGroupExpenseDo) Take() (*model.TotalPerCategoryGroupExpense, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryGroupExpense), nil
	}
}

func (t totalPerCategoryGroupExpenseDo) Last() (*model.TotalPerCategoryGroupExpense, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryGroupExpense), nil
	}
}

func (t totalPerCategoryGroupExpenseDo) Find() ([]*model.TotalPerCategoryGroupExpense, error) {
	result, err := t.DO.Find()
	return result.([]*model.TotalPerCategoryGroupExpense), err
}

func (t totalPerCategoryGroupExpenseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TotalPerCategoryGroupExpense, err error) {
	buf := make([]*model.TotalPerCategoryGroupExpense, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t totalPerCategoryGroupExpenseDo) FindInBatches(result *[]*model.TotalPerCategoryGroupExpense, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t totalPerCategoryGroupExpenseDo) Attrs(attrs ...field.AssignExpr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t totalPerCategoryGroupExpenseDo) Assign(attrs ...field.AssignExpr) *totalPerCategoryGroupExpenseDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t totalPerCategoryGroupExpenseDo) Joins(fields ...field.RelationField) *totalPerCategoryGroupExpenseDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t totalPerCategoryGroupExpenseDo) Preload(fields ...field.RelationField) *totalPerCategoryGroupExpenseDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t totalPerCategoryGroupExpenseDo) FirstOrInit() (*model.TotalPerCategoryGroupExpense, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryGroupExpense), nil
	}
}

func (t totalPerCategoryGroupExpenseDo) FirstOrCreate() (*model.TotalPerCategoryGroupExpense, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryGroupExpense), nil
	}
}

func (t totalPerCategoryGroupExpenseDo) FindByPage(offset int, limit int) (result []*model.TotalPerCategoryGroupExpense, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t totalPerCategoryGroupExpenseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t totalPerCategoryGroupExpenseDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t totalPerCategoryGroupExpenseDo) Delete(models ...*model.TotalPerCategoryGroupExpense) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *totalPerCategoryGroupExpenseDo) withDO(do gen.Dao) *totalPerCategoryGroupExpenseDo {
	t.DO = *do.(*gen.DO)
	return t
}
