// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cdlavacudeg/go-budget-guardian/model"
)

func newTotalPerCategoryExpense(db *gorm.DB, opts ...gen.DOOption) totalPerCategoryExpense {
	_totalPerCategoryExpense := totalPerCategoryExpense{}

	_totalPerCategoryExpense.totalPerCategoryExpenseDo.UseDB(db, opts...)
	_totalPerCategoryExpense.totalPerCategoryExpenseDo.UseModel(&model.TotalPerCategoryExpense{})

	tableName := _totalPerCategoryExpense.totalPerCategoryExpenseDo.TableName()
	_totalPerCategoryExpense.ALL = field.NewAsterisk(tableName)
	_totalPerCategoryExpense.Year = field.NewInt32(tableName, "Year")
	_totalPerCategoryExpense.Usuario = field.NewInt32(tableName, "Usuario")
	_totalPerCategoryExpense.IDCat = field.NewInt32(tableName, "idCat")
	_totalPerCategoryExpense.Categoria = field.NewString(tableName, "Categoria")
	_totalPerCategoryExpense.Total = field.NewFloat64(tableName, "Total")

	_totalPerCategoryExpense.fillFieldMap()

	return _totalPerCategoryExpense
}

type totalPerCategoryExpense struct {
	totalPerCategoryExpenseDo

	ALL       field.Asterisk
	Year      field.Int32
	Usuario   field.Int32
	IDCat     field.Int32
	Categoria field.String
	Total     field.Float64

	fieldMap map[string]field.Expr
}

func (t totalPerCategoryExpense) Table(newTableName string) *totalPerCategoryExpense {
	t.totalPerCategoryExpenseDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t totalPerCategoryExpense) As(alias string) *totalPerCategoryExpense {
	t.totalPerCategoryExpenseDo.DO = *(t.totalPerCategoryExpenseDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *totalPerCategoryExpense) updateTableName(table string) *totalPerCategoryExpense {
	t.ALL = field.NewAsterisk(table)
	t.Year = field.NewInt32(table, "Year")
	t.Usuario = field.NewInt32(table, "Usuario")
	t.IDCat = field.NewInt32(table, "idCat")
	t.Categoria = field.NewString(table, "Categoria")
	t.Total = field.NewFloat64(table, "Total")

	t.fillFieldMap()

	return t
}

func (t *totalPerCategoryExpense) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *totalPerCategoryExpense) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["Year"] = t.Year
	t.fieldMap["Usuario"] = t.Usuario
	t.fieldMap["idCat"] = t.IDCat
	t.fieldMap["Categoria"] = t.Categoria
	t.fieldMap["Total"] = t.Total
}

func (t totalPerCategoryExpense) clone(db *gorm.DB) totalPerCategoryExpense {
	t.totalPerCategoryExpenseDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t totalPerCategoryExpense) replaceDB(db *gorm.DB) totalPerCategoryExpense {
	t.totalPerCategoryExpenseDo.ReplaceDB(db)
	return t
}

type totalPerCategoryExpenseDo struct{ gen.DO }

func (t totalPerCategoryExpenseDo) Debug() *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Debug())
}

func (t totalPerCategoryExpenseDo) WithContext(ctx context.Context) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t totalPerCategoryExpenseDo) ReadDB() *totalPerCategoryExpenseDo {
	return t.Clauses(dbresolver.Read)
}

func (t totalPerCategoryExpenseDo) WriteDB() *totalPerCategoryExpenseDo {
	return t.Clauses(dbresolver.Write)
}

func (t totalPerCategoryExpenseDo) Session(config *gorm.Session) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Session(config))
}

func (t totalPerCategoryExpenseDo) Clauses(conds ...clause.Expression) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t totalPerCategoryExpenseDo) Returning(value interface{}, columns ...string) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t totalPerCategoryExpenseDo) Not(conds ...gen.Condition) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t totalPerCategoryExpenseDo) Or(conds ...gen.Condition) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t totalPerCategoryExpenseDo) Select(conds ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t totalPerCategoryExpenseDo) Where(conds ...gen.Condition) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t totalPerCategoryExpenseDo) Order(conds ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t totalPerCategoryExpenseDo) Distinct(cols ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t totalPerCategoryExpenseDo) Omit(cols ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t totalPerCategoryExpenseDo) Join(table schema.Tabler, on ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t totalPerCategoryExpenseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t totalPerCategoryExpenseDo) RightJoin(table schema.Tabler, on ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t totalPerCategoryExpenseDo) Group(cols ...field.Expr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t totalPerCategoryExpenseDo) Having(conds ...gen.Condition) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t totalPerCategoryExpenseDo) Limit(limit int) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t totalPerCategoryExpenseDo) Offset(offset int) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t totalPerCategoryExpenseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t totalPerCategoryExpenseDo) Unscoped() *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Unscoped())
}

func (t totalPerCategoryExpenseDo) Create(values ...*model.TotalPerCategoryExpense) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t totalPerCategoryExpenseDo) CreateInBatches(values []*model.TotalPerCategoryExpense, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t totalPerCategoryExpenseDo) Save(values ...*model.TotalPerCategoryExpense) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t totalPerCategoryExpenseDo) First() (*model.TotalPerCategoryExpense, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryExpense), nil
	}
}

func (t totalPerCategoryExpenseDo) Take() (*model.TotalPerCategoryExpense, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryExpense), nil
	}
}

func (t totalPerCategoryExpenseDo) Last() (*model.TotalPerCategoryExpense, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryExpense), nil
	}
}

func (t totalPerCategoryExpenseDo) Find() ([]*model.TotalPerCategoryExpense, error) {
	result, err := t.DO.Find()
	return result.([]*model.TotalPerCategoryExpense), err
}

func (t totalPerCategoryExpenseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TotalPerCategoryExpense, err error) {
	buf := make([]*model.TotalPerCategoryExpense, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t totalPerCategoryExpenseDo) FindInBatches(result *[]*model.TotalPerCategoryExpense, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t totalPerCategoryExpenseDo) Attrs(attrs ...field.AssignExpr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t totalPerCategoryExpenseDo) Assign(attrs ...field.AssignExpr) *totalPerCategoryExpenseDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t totalPerCategoryExpenseDo) Joins(fields ...field.RelationField) *totalPerCategoryExpenseDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t totalPerCategoryExpenseDo) Preload(fields ...field.RelationField) *totalPerCategoryExpenseDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t totalPerCategoryExpenseDo) FirstOrInit() (*model.TotalPerCategoryExpense, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryExpense), nil
	}
}

func (t totalPerCategoryExpenseDo) FirstOrCreate() (*model.TotalPerCategoryExpense, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TotalPerCategoryExpense), nil
	}
}

func (t totalPerCategoryExpenseDo) FindByPage(offset int, limit int) (result []*model.TotalPerCategoryExpense, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t totalPerCategoryExpenseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t totalPerCategoryExpenseDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t totalPerCategoryExpenseDo) Delete(models ...*model.TotalPerCategoryExpense) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *totalPerCategoryExpenseDo) withDO(do gen.Dao) *totalPerCategoryExpenseDo {
	t.DO = *do.(*gen.DO)
	return t
}
